/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connected */
        get: operations["connected_api_accounts_get"];
        put?: never;
        /**
         * Connect
         * @description Validate first, then store. A rejected key leaves nothing behind.
         *
         *     An account already connected is connected again rather than refused: its
         *     credential is replaced and it is active once more, answered 200. That is
         *     how an Epic account whose sign-in ended comes back, and how a Steam key is
         *     rotated, without losing the account's history.
         *
         *     The four provider errors are three different answers, because they are three
         *     different jobs: a wrong key and a private profile are the user's to fix and
         *     say so now, while an outage is nobody's fault and must not be reported as a
         *     bad credential — told that, someone rotates a key that was working.
         */
        post: operations["connect_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Deleted, not flagged.
         *
         *     Rule 1 is about the catalogue — a game that disappears is evidence, and a
         *     revoked session is a liability. There is nothing to audit here that
         *     `last_login_at` does not already say.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/enrichment/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run
         * @description Run the provider's step and report the run, which may have failed.
         *
         *     A failure is a status, as a sync's is, so the answer is 200 either way. 409
         *     is kept for the one thing the caller did: asking while a run is open.
         */
        post: operations["run_api_enrichment__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entitlements/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add
         * @description A manual copy on the user's `manual` account, and the stub it is a copy of (ADR-0015).
         */
        post: operations["add_api_entitlements_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entitlements/manual/{entitlement_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_entitlements_manual__entitlement_id__get"];
        /** Replace */
        put: operations["replace_api_entitlements_manual__entitlement_id__put"];
        post?: never;
        /**
         * Remove
         * @description Delete the entry, and its stub when nothing else would miss it (ADR-0031).
         *
         *     A `DELETE` rather than a removal: rule 1 guards against a platform's silence,
         *     and this is the user's own word about a row they typed in.
         */
        delete: operations["remove_api_entitlements_manual__entitlement_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entitlements/removed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Removed
         * @description Every removed copy, the most recently removed first.
         *
         *     A manual copy is never swept (rule 2), so it never appears here.
         */
        get: operations["removed_api_entitlements_removed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entitlements/{entitlement_id}/keep": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Let Go
         * @description Stop keeping a restored copy: the next successful run that does not list it removes it.
         *
         *     Nothing is removed here. The platform decides that, as it does for any
         *     other copy; this only withdraws the user's word against it.
         */
        delete: operations["let_go_api_entitlements__entitlement_id__keep_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entitlements/{entitlement_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore
         * @description Put a removed copy back, and keep it there while the platform stays silent (ADR-0030).
         *
         *     Its works count it again: a removed copy stops adding to `user_work_state`,
         *     and a work whose only copy this was comes back to the library with the
         *     state the user left on it, which a removal never touched.
         *
         *     409 for a copy that is not removed: there is nothing to undo, and a kept
         *     flag set on a live copy would be a decision the user did not make.
         */
        post: operations["restore_api_entitlements__entitlement_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/genres": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * In Library
         * @description Every genre of a work the user still owns a copy of, by name.
         *
         *     Only these: a genre offered in the panel that matches nothing in the
         *     library would be a filter that can only ever answer with nothing.
         */
        get: operations["in_library_api_genres_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image */
        get: operations["image_api_images__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_sync_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run
         * @description Sync every account of one provider and report each run, and what follows it.
         *
         *     A list rather than one run because a platform may have several accounts
         *     (M4), and one of them failing is not the others' problem — `sync_account`
         *     turns a provider failure into a run status precisely so this loop does not
         *     have to catch anything to keep rule 4.
         *
         *     `SyncInProgressError` is the only exception, and it is the caller's answer
         *     rather than a run's: the double-click that produced it wants 409, not a
         *     second run. Everything else — including a credential that will not decrypt —
         *     reaches `library_for` and comes back as a failed run, so one broken account
         *     cannot end a request that the others were about to complete.
         *
         *     Enrichment follows once any account synced, after the response has gone:
         *     the store is asked about what the sync added, and a store that is slow or
         *     down neither delays nor fails the sync that already landed (rule 4). A sync
         *     where every account failed stored nothing new, and triggers nothing. The
         *     steps are queued before the answer leaves, so a client that asks at once
         *     already sees them in progress.
         */
        post: operations["run_api_sync__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listing */
        get: operations["listing_api_views_get"];
        put?: never;
        /**
         * Create
         * @description Saved at the end of the list, in the canonical form it is read back in.
         *
         *     Stricter than reading: what is being saved now should be all understood
         *     now, so anything that would be dropped is refused instead. Dropping it here
         *     would save a different view than the one on the screen, without a word.
         */
        post: operations["create_api_views_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/views/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Reorder
         * @description Every view, each once. Anything else is a list from before a view was added or deleted.
         *
         *     A 409 rather than a best effort: placing the views it names and leaving
         *     the rest wherever they fall would be an order nobody chose.
         */
        put: operations["reorder_api_views_order_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/views/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_views__view_id__delete"];
        options?: never;
        head?: never;
        /** Rename */
        patch: operations["rename_api_views__view_id__patch"];
        trace?: never;
    };
    "/api/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listing
         * @description One page, keyed on the order's value, `sort_key` and `id` rather than an offset.
         *
         *     An offset re-reads and discards every row before the page, so the last page
         *     of a large library costs the most; and a sync landing a new title mid-scroll
         *     shifts every later page by one, which shows up as a duplicated or skipped
         *     row. A keyset does neither: `ix_work_sort_key_id` seeks straight to the
         *     position and the page is defined by content rather than by count.
         *
         *     The key and not `sort_title` itself, because the database compares bytes:
         *     "ARC Raiders" would file ahead of "Amnesia", and a trademark sign would split
         *     one series into two blocks (ADR-0018).
         *
         *     `q` and the filters narrow the listing without changing its order or its
         *     cursor: a filtered page is keyed as the unfiltered one is, so a search
         *     pages as the library does. The filters are declared in `ludarium.filters`,
         *     the orders in `ludarium.sorting`.
         */
        get: operations["listing_api_works_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/works/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Detail
         * @description One work, if it is in the user's library.
         *
         *     404 for a work that does not exist and for one only removed copies point
         *     at, alike: the listing would not show it, so neither does this, and the
         *     answer does not say which of the two it was.
         */
        get: operations["detail_api_works__work_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/works/{work_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update State
         * @description Change what the user decides about a work, and answer with the work as it now is.
         *
         *     The same 404 as the detail view: a work that is not in the library has no
         *     state worth keeping, and the answer does not say whether it exists.
         *
         *     A work with no state row gets one. Nothing enforces the row (`_owned_works`
         *     outer-joins it for that reason), so its absence is a gap to fill, not a
         *     missing work.
         */
        patch: operations["update_state_api_works__work_id__state_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountResponse
         * @description What the frontend may know about a connected account.
         *
         *     `credentials` is the mask and nothing else. There is no field here that
         *     could carry the ciphertext either: an encrypted secret in a response is
         *     still the secret, one key away.
         */
        AccountResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Credentials */
            credentials: string | null;
            /** External Account Id */
            external_account_id: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Label */
            label: string;
            /** Last Error */
            last_error: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Provider */
            provider: string;
            status: components["schemas"]["SyncStatus"];
        };
        /**
         * CompanyRole
         * @enum {string}
         */
        CompanyRole: "developer" | "publisher" | "porting" | "support";
        /** ConnectRequest */
        ConnectRequest: {
            /**
             * Credentials
             * Format: password
             */
            credentials: string;
            /**
             * External Account Id
             * @default
             */
            external_account_id: string;
            /**
             * Label
             * @default Main
             */
            label: string;
            /** Provider */
            provider: string;
        };
        /**
         * Cover
         * @description A cover at two sizes, for `srcset`: `url` at its own size, `url_2x` at twice it.
         */
        Cover: {
            /** Height */
            height: number;
            /** Url */
            url: string;
            /** Url 2X */
            url_2x: string | null;
            /** Width */
            width: number;
        };
        /**
         * Credit
         * @description One company and every role it played in the work.
         */
        Credit: {
            /** Name */
            name: string;
            /** Roles */
            roles: components["schemas"]["CompanyRole"][];
        };
        /**
         * Direction
         * @enum {string}
         */
        Direction: "asc" | "desc";
        /**
         * EntitlementSummary
         * @description One copy the user owns, and where it came from. The platform column of the table.
         */
        EntitlementSummary: {
            /** Id */
            id: number;
            /** Kept */
            kept: boolean;
            /** Playtime Minutes */
            playtime_minutes: number | null;
            /** Provider */
            provider: string;
            /** Provider Item Id */
            provider_item_id: string | null;
            /** Provider Name */
            provider_name: string;
            /** Provider Title */
            provider_title: string;
            /** Store Label */
            store_label: string | null;
            /** Store Url */
            store_url: string | null;
        };
        /** GenreSummary */
        GenreSummary: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Database */
            database: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /**
         * Hidden
         * @description Whether the works the user hid are in the listing.
         * @enum {string}
         */
        Hidden: "exclude" | "include" | "only";
        /**
         * ItemKind
         * @enum {string}
         */
        ItemKind: "game" | "dlc" | "demo" | "playtest" | "soundtrack" | "video" | "tool" | "mod";
        /**
         * LoginRequest
         * @description Bounded, because this is the one endpoint that answers before authenticating.
         *
         *     Not because argon2's cost scales with the input — measured, a 10 MB password
         *     costs 62 ms against 49 ms for a short one, since the memory-hard phase is
         *     fixed. The reason is upstream of that: an unbounded string is buffered whole
         *     and carried through validation before anything gets to decide it is wrong.
         */
        LoginRequest: {
            /**
             * Password
             * Format: password
             */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * ManualEntry
         * @description A copy no platform knows about, as the user describes it.
         *
         *     The whole entry on every write, so the form that edits one sends what it
         *     shows: a field left out is its default, never "unchanged".
         */
        ManualEntry: {
            /** @default game */
            item_kind: components["schemas"]["ItemKind"];
            /** @default owned */
            ownership_type: components["schemas"]["OwnershipType"];
            /** Release Year */
            release_year?: number | null;
            /** Store Label */
            store_label?: string | null;
            title: components["schemas"]["Title"];
        };
        /**
         * ManualEntryResponse
         * @description The entry as the user last wrote it, and the work it is a copy of.
         */
        ManualEntryResponse: {
            /** Id */
            id: number;
            item_kind: components["schemas"]["ItemKind"] | null;
            ownership_type: components["schemas"]["OwnershipType"];
            /** Release Year */
            release_year: number | null;
            /** Store Label */
            store_label: string | null;
            /** Title */
            title: string;
            /** Work Id */
            work_id: number;
        };
        Name: string;
        /**
         * OwnershipType
         * @enum {string}
         */
        OwnershipType: "owned" | "subscription" | "free" | "family_shared" | "trial" | "physical";
        /**
         * PlayStatus
         * @enum {string}
         */
        PlayStatus: "not_started" | "playing" | "completed" | "mastered" | "dropped" | "on_hold" | "wishlist";
        /** ProviderStatusResponse */
        ProviderStatusResponse: {
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Key */
            key: string;
            /** Last Error */
            last_error: string | null;
            /** Last Success At */
            last_success_at: string | null;
            status: components["schemas"]["SyncStatus"];
        };
        /**
         * RemovedEntitlement
         * @description A copy a successful run no longer saw, and when.
         */
        RemovedEntitlement: {
            /** Account Label */
            account_label: string;
            /** Id */
            id: number;
            /** Provider */
            provider: string;
            /** Provider Name */
            provider_name: string;
            /** Provider Title */
            provider_title: string;
            /**
             * Removed At
             * Format: date-time
             */
            removed_at: string;
            /** Removed By Run Id */
            removed_by_run_id: number | null;
            /** Work Id */
            work_id: number | null;
            /** Work Title */
            work_title: string | null;
        };
        /** SavedViewResponse */
        SavedViewResponse: {
            /** Dropped */
            dropped: string[];
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Position */
            position: number;
            /** Query */
            query: string;
        };
        /**
         * Score
         * @description A Metacritic score and the page of the source it came from, which is RAWG.
         *
         *     One object so the two cannot be separated: RAWG's terms require an active
         *     link wherever its data is shown, and a score the API hands out without its
         *     link is a score some client will show without it.
         */
        Score: {
            /** Source Name */
            source_name: string;
            /** Source Url */
            source_url: string;
            /** Value */
            value: number;
        };
        /**
         * SessionResponse
         * @description What the frontend needs to render a signed-in shell. The token is in the cookie.
         */
        SessionResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Username */
            username: string;
        };
        /**
         * Sort
         * @enum {string}
         */
        Sort: "title" | "metacritic" | "steam_reviews" | "playtime" | "last_played" | "release_date";
        /**
         * StateUpdate
         * @description Any subset of what the user decides about a work.
         *
         *     A field left out is left alone; one sent as null is cleared. That is the
         *     difference `model_fields_set` keeps, and the reason every field has a
         *     default. `play_status` and the two flags are never null, so a null for them
         *     is refused by their types.
         */
        StateUpdate: {
            /**
             * Is Favourite
             * @default false
             */
            is_favourite: boolean;
            /**
             * Is Hidden
             * @default false
             */
            is_hidden: boolean;
            /** Notes */
            notes?: string | null;
            /** @default not_started */
            play_status: components["schemas"]["PlayStatus"];
            /** Rating */
            rating?: number | null;
        };
        /**
         * SteamRating
         * @description The Steam store's verdict on an app's user reviews, worst first, as the store orders it.
         * @enum {string}
         */
        SteamRating: "overwhelmingly_negative" | "very_negative" | "negative" | "mostly_negative" | "mixed" | "mostly_positive" | "positive" | "very_positive" | "overwhelmingly_positive";
        /**
         * SteamReviews
         * @description The Steam store's verdict on one of the work's apps, and where to read the reviews.
         *
         *     `rating` is the verdict's value rather than Steam's label, which the store
         *     translates: the client names it in the user's language. Null where the
         *     store gave none, over too few reviews: the percentage stands with its
         *     count, which says how little it rests on (ADR-0029).
         */
        SteamReviews: {
            /** Count */
            count: number;
            /** Percent */
            percent: number;
            rating: components["schemas"]["SteamRating"] | null;
            /** Url */
            url: string;
        };
        /**
         * SyncErrorKind
         * @description Why a run failed, in the terms of who can fix it.
         * @enum {string}
         */
        SyncErrorKind: "credentials" | "not_visible" | "rate_limited" | "unavailable" | "malformed" | "other";
        /**
         * SyncOverviewResponse
         * @description Both halves in one call, because the panel shows them together.
         *
         *     A provider's health without its runs cannot say *what* failed, and the runs
         *     without the provider row cannot say whether it has ever worked.
         */
        SyncOverviewResponse: {
            /** Enriching */
            enriching: string[];
            /** Providers */
            providers: components["schemas"]["ProviderStatusResponse"][];
            /** Runs */
            runs: components["schemas"]["SyncRunResponse"][];
        };
        /** SyncResponse */
        SyncResponse: {
            /** Enriching */
            enriching: string[];
            /** Runs */
            runs: components["schemas"]["SyncRunResponse"][];
        };
        /** SyncRunResponse */
        SyncRunResponse: {
            /** Account Id */
            account_id: number | null;
            error_kind: components["schemas"]["SyncErrorKind"] | null;
            /** Error Text */
            error_text: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Items Added */
            items_added: number;
            /** Items Removed */
            items_removed: number;
            /** Items Seen */
            items_seen: number;
            /** Items Skipped */
            items_skipped: number;
            /** Items Updated */
            items_updated: number;
            /** Provider */
            provider: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SyncStatus"];
            trigger: components["schemas"]["SyncTrigger"];
        };
        /**
         * SyncStatus
         * @enum {string}
         */
        SyncStatus: "pending" | "running" | "success" | "partial" | "failed";
        /**
         * SyncTrigger
         * @enum {string}
         */
        SyncTrigger: "manual" | "scheduled" | "ingest" | "import";
        Title: string;
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ViewCreate */
        ViewCreate: {
            name: components["schemas"]["Name"];
            /** Query */
            query: string;
        };
        /**
         * ViewOrder
         * @description Every view's id, in the order they should be listed.
         */
        ViewOrder: {
            /** Ids */
            ids: number[];
        };
        /** ViewRename */
        ViewRename: {
            name: components["schemas"]["Name"];
        };
        /**
         * WorkDetail
         * @description One work with what the grid leaves out: its summary, date and who made it (#54).
         */
        WorkDetail: {
            /** Companies */
            companies: components["schemas"]["Credit"][];
            /** Completed At */
            completed_at: string | null;
            cover: components["schemas"]["Cover"] | null;
            /** Entitlements */
            entitlements: components["schemas"]["EntitlementSummary"][];
            /** Genres */
            genres: components["schemas"]["GenreSummary"][];
            /** Id */
            id: number;
            /** Is Favourite */
            is_favourite: boolean;
            /** Is Hidden */
            is_hidden: boolean;
            /** Is Matched */
            is_matched: boolean;
            item_kind: components["schemas"]["ItemKind"] | null;
            /** Last Played At */
            last_played_at: string | null;
            metacritic: components["schemas"]["Score"] | null;
            /** Notes */
            notes: string | null;
            play_status: components["schemas"]["PlayStatus"];
            /** Playtime Minutes */
            playtime_minutes: number;
            /** Rating */
            rating: number | null;
            /** Release Date */
            release_date: string | null;
            /** Release Year */
            release_year: number | null;
            /** Sort Title */
            sort_title: string;
            /** Started At */
            started_at: string | null;
            steam_reviews: components["schemas"]["SteamReviews"] | null;
            /** Summary */
            summary: string | null;
            /** Title */
            title: string;
        };
        /** WorkSummary */
        WorkSummary: {
            cover: components["schemas"]["Cover"] | null;
            /** Entitlements */
            entitlements: components["schemas"]["EntitlementSummary"][];
            /** Id */
            id: number;
            /** Is Favourite */
            is_favourite: boolean;
            /** Is Hidden */
            is_hidden: boolean;
            /** Is Matched */
            is_matched: boolean;
            item_kind: components["schemas"]["ItemKind"] | null;
            /** Last Played At */
            last_played_at: string | null;
            metacritic: components["schemas"]["Score"] | null;
            play_status: components["schemas"]["PlayStatus"];
            /** Playtime Minutes */
            playtime_minutes: number;
            /** Release Year */
            release_year: number | null;
            /** Sort Title */
            sort_title: string;
            steam_reviews: components["schemas"]["SteamReviews"] | null;
            /** Title */
            title: string;
        };
        /** WorksPage */
        WorksPage: {
            /** Next Cursor */
            next_cursor: string | null;
            /** Works */
            works: components["schemas"]["WorkSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    connected_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_enrichment__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_api_entitlements_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_entitlements_manual__entitlement_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entitlement_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replace_api_entitlements_manual__entitlement_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entitlement_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualEntryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_api_entitlements_manual__entitlement_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entitlement_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    removed_api_entitlements_removed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RemovedEntitlement"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    let_go_api_entitlements__entitlement_id__keep_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entitlement_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_api_entitlements__entitlement_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entitlement_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    in_library_api_genres_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenreSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    image_api_images__image_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description The image file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_sync_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_sync__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listing_api_views_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_views_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_api_views_order_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewOrder"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_views__view_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_api_views__view_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                view_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ViewRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedViewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listing_api_works_get: {
        parameters: {
            query?: {
                platform?: string[];
                kind?: components["schemas"]["ItemKind"][];
                genre?: string[];
                metacritic_min?: number | null;
                metacritic_max?: number | null;
                steam_min?: number | null;
                steam_max?: number | null;
                steam_reviews_min?: number;
                year_min?: number | null;
                year_max?: number | null;
                status?: components["schemas"]["PlayStatus"][];
                hidden?: components["schemas"]["Hidden"];
                playtime_min?: number | null;
                playtime_max?: number | null;
                limit?: number;
                cursor?: string | null;
                q?: string | null;
                sort?: components["schemas"]["Sort"];
                order?: components["schemas"]["Direction"];
            };
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorksPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_works__work_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_state_api_works__work_id__state_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: number;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
