/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Connected */
        get: operations["connected_api_accounts_get"];
        put?: never;
        /**
         * Connect
         * @description Validate first, then store. A rejected key leaves nothing behind.
         *
         *     The four provider errors are three different answers, because they are three
         *     different jobs: a wrong key and a private profile are the user's to fix and
         *     say so now, while an outage is nobody's fault and must not be reported as a
         *     bad credential — told that, someone rotates a key that was working.
         */
        post: operations["connect_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Deleted, not flagged.
         *
         *     Rule 1 is about the catalogue — a game that disappears is evidence, and a
         *     revoked session is a liability. There is nothing to audit here that
         *     `last_login_at` does not already say.
         */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Overview */
        get: operations["overview_api_sync_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run
         * @description Sync every account of one provider and report each run.
         *
         *     A list rather than one run because a platform may have several accounts
         *     (M4), and one of them failing is not the others' problem — `sync_account`
         *     turns a provider failure into a run status precisely so this loop does not
         *     have to catch anything to keep rule 4.
         *
         *     `SyncInProgressError` is the only exception, and it is the caller's answer
         *     rather than a run's: the double-click that produced it wants 409, not a
         *     second run. Everything else — including a credential that will not decrypt —
         *     reaches `library_for` and comes back as a failed run, so one broken account
         *     cannot end a request that the others were about to complete.
         */
        post: operations["run_api_sync__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listing
         * @description One page, keyed on `(sort_title, id)` rather than an offset.
         *
         *     An offset re-reads and discards every row before the page, so the last page
         *     of a large library costs the most; and a sync landing a new title mid-scroll
         *     shifts every later page by one, which shows up as a duplicated or skipped
         *     row. A keyset does neither: `ix_work_sort_title_id` seeks straight to the
         *     position and the page is defined by content rather than by count.
         */
        get: operations["listing_api_works_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AccountResponse
         * @description What the frontend may know about a connected account.
         *
         *     `credentials` is the mask and nothing else. There is no field here that
         *     could carry the ciphertext either: an encrypted secret in a response is
         *     still the secret, one key away.
         */
        AccountResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Credentials */
            credentials: string | null;
            /** External Account Id */
            external_account_id: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Label */
            label: string;
            /** Last Success At */
            last_success_at: string | null;
            /** Provider */
            provider: string;
        };
        /** ConnectRequest */
        ConnectRequest: {
            /**
             * Credentials
             * Format: password
             */
            credentials: string;
            /** External Account Id */
            external_account_id: string;
            /**
             * Label
             * @default Main
             */
            label: string;
            /** Provider */
            provider: string;
        };
        /**
         * EntitlementSummary
         * @description One copy the user owns, and where it came from. The platform column of the table.
         */
        EntitlementSummary: {
            /** Id */
            id: number;
            /** Playtime Minutes */
            playtime_minutes: number | null;
            /** Provider */
            provider: string;
            /** Provider Item Id */
            provider_item_id: string | null;
            /** Provider Name */
            provider_name: string;
            /** Provider Title */
            provider_title: string;
            /** Store Url */
            store_url: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Database */
            database: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
        };
        /**
         * ItemKind
         * @enum {string}
         */
        ItemKind: "game" | "dlc" | "demo" | "soundtrack" | "video" | "tool" | "mod";
        /**
         * LoginRequest
         * @description Bounded, because this is the one endpoint that answers before authenticating.
         *
         *     Not because argon2's cost scales with the input — measured, a 10 MB password
         *     costs 62 ms against 49 ms for a short one, since the memory-hard phase is
         *     fixed. The reason is upstream of that: an unbounded string is buffered whole
         *     and carried through validation before anything gets to decide it is wrong.
         */
        LoginRequest: {
            /**
             * Password
             * Format: password
             */
            password: string;
            /** Username */
            username: string;
        };
        /**
         * PlayStatus
         * @enum {string}
         */
        PlayStatus: "not_started" | "playing" | "completed" | "mastered" | "dropped" | "on_hold" | "wishlist";
        /** ProviderStatusResponse */
        ProviderStatusResponse: {
            /** Display Name */
            display_name: string;
            /** Enabled */
            enabled: boolean;
            /** Key */
            key: string;
            /** Last Error */
            last_error: string | null;
            /** Last Success At */
            last_success_at: string | null;
            status: components["schemas"]["SyncStatus"];
        };
        /**
         * SessionResponse
         * @description What the frontend needs to render a signed-in shell. The token is in the cookie.
         */
        SessionResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Username */
            username: string;
        };
        /**
         * SyncOverviewResponse
         * @description Both halves in one call, because the panel shows them together.
         *
         *     A provider's health without its runs cannot say *what* failed, and the runs
         *     without the provider row cannot say whether it has ever worked.
         */
        SyncOverviewResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderStatusResponse"][];
            /** Runs */
            runs: components["schemas"]["SyncRunResponse"][];
        };
        /** SyncRunResponse */
        SyncRunResponse: {
            /** Account Id */
            account_id: number | null;
            /** Error Text */
            error_text: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /** Items Added */
            items_added: number;
            /** Items Removed */
            items_removed: number;
            /** Items Seen */
            items_seen: number;
            /** Items Updated */
            items_updated: number;
            /** Provider */
            provider: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["SyncStatus"];
            trigger: components["schemas"]["SyncTrigger"];
        };
        /**
         * SyncStatus
         * @enum {string}
         */
        SyncStatus: "pending" | "running" | "success" | "partial" | "failed";
        /**
         * SyncTrigger
         * @enum {string}
         */
        SyncTrigger: "manual" | "scheduled" | "ingest" | "import";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkSummary */
        WorkSummary: {
            /** Entitlements */
            entitlements: components["schemas"]["EntitlementSummary"][];
            /** Id */
            id: number;
            /** Is Favourite */
            is_favourite: boolean;
            /** Is Hidden */
            is_hidden: boolean;
            /** Is Matched */
            is_matched: boolean;
            item_kind: components["schemas"]["ItemKind"];
            /** Last Played At */
            last_played_at: string | null;
            play_status: components["schemas"]["PlayStatus"];
            /** Playtime Minutes */
            playtime_minutes: number;
            /** Release Year */
            release_year: number | null;
            /** Sort Title */
            sort_title: string;
            /** Title */
            title: string;
        };
        /** WorksPage */
        WorksPage: {
            /** Next Cursor */
            next_cursor: string | null;
            /** Works */
            works: components["schemas"]["WorkSummary"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    connected_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connect_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    overview_api_sync_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncOverviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_api_sync__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRunResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listing_api_works_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                ludarium_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorksPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
